#!/usr/bin/env ruby
#
# Command to run the specs the correct way when triggered from the turbux vim plugin.

command = "rspec --color --tty"
command += " #{ARGV.first}"

exit(1) unless system(command)
